### ISSUE TITLE
Emails to say that everything is up to date seems spammy

### ISSUE THREAD

**Issue by lpil** [hexfaktor/hex_faktor_web#13]
I would prefer not to be emailed by default when everything is up to date.

**Comment by rrrene** [comment]
There is an option under "Settings" to get e-mail summaries daily **if** there were updates to your projects. Check it out! :+1:

P.S. I don't think the term "spammy" is correct in this context. There are several services which send out mails no matter what (to report a healthy status). I personally get half a dozen emails on monday which I expect, especially to see that everything is running as expected.

**Comment by lpil** [comment]
I certainly think spammy is the right word, and I think this behaviour should be opt-in.

**Comment by rrrene** [comment]
Maybe you're right. It's just historical that I implemented the weekly report first, so that got to be the default.

Maybe "no emails" should be the default, so people choose their setting intentionally?

**Comment by lpil** [comment]
I think emails when Anton needs to be taken is a nice middle ground, providing they are sent as a digest, like they currently are.

**Comment by optikfluffel** [comment]
I for one like the way Travis is handling this, if something is broken, after fixing, they will send **one** email that everything is ok now and then stops bothering until something isn't fine anymore. Maybe that would be something to think about?

**Comment by rrrene** [comment]
Mmmh, that is actually something I like as well. It is more complicated than sending a weekly report no matter what, but this might be worth investigating.

So basically we would send an email when something "breaks" due to a newer package release and send another email as soon as the user fixed their dependencies. With Travis, however, you also get the (thankfully) annoying emails each time you push a broken build. I think we would _not_ want that behaviour for this service?

Maybe @lpil's idea of having a checkbox that says "only receive reports if something is wrong" is the middle ground here?

**Comment by optikfluffel** [comment]
> With Travis, however, you also get the (thankfully) annoying emails each time you push a broken build. I think we would not want that behaviour for this service?

Actually I'd prefer that behaviour of constant nagging if something is "broken", because otherwise I'd leave broken stuff lying around, but I can see that this a personal motivational problem and would annoy other people 😸

Maybe even a different behaviour depending on the kind of update (following semver?) would be cool.
